name: Desplegar Sitio Web Github Pages

on:
  push:
    branches:
      -main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Hacer Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar node
        uses: actions/setup-node@v3
        with:
          node-version: 17
      - run: npm install
      - run: npm install
      - run: npm test

      - name: Desplegar en github pages
        uses: peaceiris/action-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          publish_dir: ./
          allow_empty_commit: true